[providers]
swift = "*"

[variables]
NIXPACKS_SWIFT_VERSION = "5.9"

[phases.setup]
nixPkgs = ["swift", "libgcc"]

[phases.build]
cmds = [
    "rm -f Package.resolved",
    "swift package resolve",
    "swift build -c release --static-swift-stdlib || swift build -c release"
]

[phases.start]
cmd = "./.build/release/Lawrence"

[ports]
8080 = "8080"